### ISSUE TITLE
Something is leaky

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/gitamp#36]
The cause of this may or may not be #35

```
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted at /opt/php-src/ext/date/lib/timelib.c:42 (tried to allocate 320 bytes) in /opt/gitamp/vendor/amphp/aerys/lib/Ticker.php on line 64
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: PHP Fatal error:  Uncaught LogicException: Cannot run() recursively; event reactor already active in /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php:52
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: Stack trace:
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: #0 /opt/gitamp/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: #1 /opt/gitamp/vendor/amphp/aerys/lib/Process.php(129): Amp\run(Object(Closure))
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: #2 [internal function]: Aerys\Process->Aerys\{closure}()
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]: #3 {main}
Feb 10 16:37:49 GitAmp-Ubuntu php[12165]:   thrown in /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php on line 52
```

**Comment by ekinhbayar** [comment]
Another one I spotted few days ago:

```
GitAmp-Ubuntu php[21826]: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted at /opt/php-src/Zend/zend_string.h:122 (tried to allocate 173512 bytes) in /opt/gitamp/vendor/amphp/artax/lib/Client.php on line 634
GitAmp-Ubuntu php[21826]: PHP Fatal error:  Uncaught LogicException: Cannot run() recursively; event reactor already active in /opt/gitamp/vendor/amphp/amp/lib/UvReactor.php:67
GitAmp-Ubuntu php[21826]: Stack trace:
GitAmp-Ubuntu php[21826]: #0 /opt/gitamp/vendor/amphp/amp/lib/functions.php(46): Amp\UvReactor->run(Object(Closure))
GitAmp-Ubuntu php[21826]: #1 /opt/gitamp/vendor/amphp/aerys/lib/Process.php(129): Amp\run(Object(Closure))
GitAmp-Ubuntu php[21826]: #2 [internal function]: Aerys\Process->Aerys\{closure}()
GitAmp-Ubuntu php[21826]: #3 {main}
GitAmp-Ubuntu php[21826]:   thrown in /opt/gitamp/vendor/amphp/amp/lib/UvReactor.php on line 67
```
